WITH provider AS (
    SELECT id
    FROM "service_providers"
    WHERE name = 'linear'
),
target AS (
    SELECT id,
           metadata,
           COALESCE(metadata #> '{ingestion,http,skipItems}', '[]'::jsonb) AS skip_items
    FROM "service_components"
    WHERE provider_id IN (SELECT id FROM provider)
      AND kind = 'action'
      AND name = 'linear_issue_created'
),
filtered AS (
    SELECT
        id,
        COALESCE(
            (
                SELECT jsonb_agg(item)
                FROM jsonb_array_elements(skip_items) AS item
                WHERE NOT (
                    item ->> 'path' = 'description'
                    AND item ->> 'contains' = '<-- AREA_LINEAR_AUTOGENERATED -->'
                )
            ),
            '[]'::jsonb
        ) AS remaining
    FROM target
)
UPDATE "service_components" AS sc
SET "metadata" = CASE
        WHEN filtered.remaining = '[]'::jsonb THEN sc.metadata #- '{ingestion,http,skipItems}'
        ELSE jsonb_set(
            sc.metadata,
            '{ingestion,http,skipItems}',
            filtered.remaining,
            true
        )
    END,
    "updated_at" = NOW()
FROM filtered
WHERE sc.id = filtered.id;
