WITH provider AS (
    SELECT id
    FROM "service_providers"
    WHERE name = 'linear'
),
target AS (
    SELECT id,
           metadata,
           COALESCE(metadata #> '{ingestion,http,skipItems}', '[]'::jsonb) AS skip_items
    FROM "service_components"
    WHERE provider_id IN (SELECT id FROM provider)
      AND kind = 'action'
      AND name = 'linear_issue_created'
),
payload AS (
    SELECT id,
           CASE
               WHEN skip_items @> jsonb_build_array(jsonb_build_object('path', 'description', 'contains', '<-- AREA_LINEAR_AUTOGENERATED -->'))
               THEN skip_items
               ELSE skip_items || jsonb_build_array(
                   jsonb_build_object(
                       'path', 'description',
                       'contains', '<-- AREA_LINEAR_AUTOGENERATED -->'
                   )
               )
           END AS updated_skip_items
    FROM target
)
UPDATE "service_components" AS sc
SET "metadata" = jsonb_set(
        sc.metadata,
        '{ingestion,http,skipItems}',
        payload.updated_skip_items,
        true
    ),
    "updated_at" = NOW()
FROM payload
WHERE sc.id = payload.id;
